### ISSUE TITLE
how i can Download 

### ISSUE THREAD

**Issue by prince911** [thecoder75/liveme-tools#123]
how i can Download any help ineed some pic or guidance

**Comment by prince911** [comment]
iam use linux

**Comment by thecoder75** [comment]
Click on the **Releases** link and download the `tar.bz2` archive.  Extract it using the extraction program that comes with your Linux distribution.

Navigate to the newly created folder and execute `livemetools`.

**Comment by prince911** [comment]
yes i  know i can watch how i can Download

**Comment by prince911** [comment]
Some accounts do not appear

But appear on the phone

**Comment by prince911** [comment]
Uncaught Exception:
TypeError: Cannot read property 'uid' of undefined
    at update_favorites_list (/home/mostafa/Downloads/LiveMeTools-6.2.1/resources/app.asar/custom_modules/Favorites/index.js:167:27)
    at Object.update (/home/mostafa/Downloads/LiveMeTools-6.2.1/resources/app.asar/custom_modules/Favorites/index.js:84:3)
    at click (/home/mostafa/Downloads/LiveMeTools-6.2.1/resources/app.asar/index.js:850:44)
    at MenuItem.click (/home/mostafa/Downloads/LiveMeTools-6.2.1/resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/home/mostafa/Downloads/LiveMeTools-6.2.1/resources/electron.asar/browser/api/menu.js:121:15)

**Comment by thecoder75** [comment]
You need to have both `ffmpeg` and `ffprobe` installed.  Also, I would recommend you download and run the 6.3.3 release as it is more stable and less buggy then the release you referenced above.
