### ISSUE TITLE
Downloads not working in 5.0.x releases!

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#59]
Received a couple reports now downloads aren't working.

**Comment by thecoder75** [comment]
Found a reference to an old path in the importlist.html file that was causing VideoID List Import to break.

Also I've disabled the FFMPEG detection code for now as it may be causing download issues for some people too.

May be related to these Issues:
- #53 
- #56

**Comment by thecoder75** [comment]
Was informed that this issue has resurfaced in the macOS version since 5.0.2.  I believe this is when the FFMPEG downloader module was added along with a couple other minor changes to the downloader init which may be at fault.

**Comment by polydragon** [comment]
I've been looking through everything you did but I can't figure out what state this is in with the FFMPEG requirement. It seems there's a version in `build/` but that doesn't get packaged with the app. The `shell` and `ffmpeg-downloader` parts are already removed so I'm not sure what you were planning on doing.

**Comment by thecoder75** [comment]
The versions in the build directory are manually added when I create the final builds.

The shell and fffmpeg-downloader were attempts at adding an auto-downloader and installer if ffmpeg was not found but they kept failing on me.

**Comment by polydragon** [comment]
I've added some code that *should* work, but it all depends on where it bundles the ffmpeg with the build commands. I am unable to build a Linux or Mac version on Windows, so I can't see if it bundles the correct executable.

Though looking through your experimentation on earlier builds, the 5.0.7 Windows .zip contains the Mac executable, not the Windows one. So all I can confirm is the built version that was compiled on a Windows machine does work perfectly.

**Comment by thecoder75** [comment]
You updated a module recently or did something but now **all builds fail** with the following message:
```
electron-builder 19.28.4
Error: schema with key or id "http://json-schema.org/draft-04/schema" already exists
    at checkUnique (/Users/richard/Repositories/liveme-tools/src/node_modules/ajv/lib/ajv.js:410:13)
    at addSchema (/Users/richard/Repositories/liveme-tools/src/node_modules/ajv/lib/ajv.js:132:5)
    at Ajv.addMetaSchema (/Users/richard/Repositories/liveme-tools/src/node_modules/ajv/lib/ajv.js:145:5)
    at /Users/richard/Repositories/liveme-tools/src/node_modules/read-config-file/src/main.ts:122:7
    at Generator.next (<anonymous>)
From previous event:
    at validateConfig (/Users/richard/Repositories/liveme-tools/src/node_modules/read-config-file/out/main.js:133:22)
    at /Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/src/util/config.ts:103:3
    at Generator.next (<anonymous>)
From previous event:
    at validateConfig (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/util/config.js:100:22)
    at /Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/src/packager.ts:146:11
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/packager.js:257:11)
    at /Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/src/builder.ts:286:40
    at Generator.next (<anonymous>)
    at build (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.self.runCommand (/Users/richard/Repositories/liveme-tools/src/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/richard/Repositories/liveme-tools/src/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/richard/Repositories/liveme-tools/src/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/richard/Repositories/liveme-tools/src/node_modules/electron-builder/out/cli/cli.js:151:418)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by thecoder75** [comment]
Closing this as now have tested and updated code that allows us to use our own manually bundled FFMPEG for downloading.

**Comment by polydragon** [comment]
Regarding commit db5bc070621badbe6bc8cfd51c86e9a14c0110fd:

Does it put the ffmpeg executable directly inside the resources folder for you? (Like `resources\ffmpeg.exe`) When I run `dist-win` it places here `resources\build\ffmpeg.exe`. If it does then it's not an issue as I can't build the Mac/Linux builds anyway so I can't really release a full version, I'm just curious as it seems inconsistent.

**Comment by thecoder75** [comment]
Updated the path so no matter which version built its included in the Resource directory only and the module points to the correct version as well.

Have built and verfied it being in the correct spot.

**Comment by polydragon** [comment]
I didn't know you had other commits you hadn't pushed yet. It makes more sense now.
